SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) >= 8 AND MONTH(START_DATE) < 11
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AND MONTH(START_DATE) >= 8 AND MONTH(START_DATE) < 11
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC;