WITH MAXS AS (
SELECT MAX(SIZE_OF_COLONY) AS MAXSIZE
, YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
GROUP BY YEAR )

SELECT M.YEAR
, (M.MAXSIZE - E.SIZE_OF_COLONY) YEAR_DEV
, E.ID
FROM MAXS M INNER JOIN ECOLI_DATA E
ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY M.YEAR, YEAR_DEV