SELECT FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) as total
      FROM (SELECT FLAVOR, TOTAL_ORDER FROM JULY
      UNION ALL
      SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF) as COMBINED_TABLE
      GROUP BY FLAVOR
      ORDER BY total DESC
      ) as TOTAL_TABLE
LIMIT 3;